name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        run: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifact
        run: actions/upload-artifact@v3
        with:
          name: build-files
          path: build